spring.application.name=bqp-validate-excel
server.port=8080

# Cấu hình Multipart Upload (cho phép file PDF lên đến 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Thymeleaf Caching (tắt khi phát triển/chạy exe)
spring.thymeleaf.cache=false
