
spring.application.name=bqp-validate-excel

# Cấu hình giới hạn kích thước file tải lên (khắc phục lỗi 413 Content Too Large)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Cấu hình bộ đệm máy chủ web Tomcat
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=-1
